language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

addons:
  code_climate:
    repo_token: c21da154ca2c9c9e4199d1aced2c3c687891c3f032bd00dbe036e47d9220a270


sudo: false

before_install:
  - composer selfupdate
  - composer install --dev --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "demateus@gmail.com"